package com.bw.composetodo.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.bw.composetodo.util.Constants.DATABASE_TABLE

/**
 Entity annotation tells Room we will have a table with columns
 ID, title, description, priority
 */

@Entity(tableName = DATABASE_TABLE)
data class ToDoTask(
    @PrimaryKey(autoGenerate = true)
    /** ID will be autogenerated by room library */
    val id: Int = 0,
    val title: String,
    val description: String,
    val priority: Priority
)